defaults:
    - default
    - data: kitti_360
    - _self_

name: "eval_bev_sem"
model: "bev_sem"
checkpoint: "out/kitti_360/pretrained"
#checkpoint: "out/kitti_360/kitti_360_backend-None-1_20230824-093207"


log_every: 10
batch_size: 1
num_workers: 1


data:
    image_size: [192, 640]
    data_3d_bboxes: false
    data_segmentation: false
    data_fisheye: false
    data_stereo: false
    data_fc: 1
    is_preprocessed: false
    data_bev_sem: true

model_conf:
    arch: "SBTSNet"
    use_code: true

    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true

    encoder:
        type: "semantic"
        freeze: false
        pretrained: true
        resnet_layers: 50 # 50
        num_ch_dec: [32,32,64,128,256]
        d_out: 64

    mlp_coarse:
        type : "resnet"
        n_blocks : 0
        d_hidden : 64

    mlp_fine:
        type : "empty"
        n_blocks : 1
        d_hidden : 128

    mlp_class:
        type : "class_resnet"
        n_blocks : 0
        d_hidden : 64
        n_classes: 10
        class_names: ["unlabeled", "road", "sidewalk", "vegetation", "terrain", "sky", "car", "person", "truck", "wall"]

    z_near: 3
    z_far: 80
    ray_batch_size: 256
    code_mode: z
    inv_z: true
    learn_empty: false

    n_frames_encoder: 1
    n_frames_render: 1

    sample_color: true

renderer:
    n_coarse : 64
    n_fine : 0
    n_fine_depth : 0
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    hard_alpha_cap: true
