defaults:
    - default
    - data: kitti_360
    - _self_

name: "kitti_360"
model: "bts"
output_path: "out/kitti_360"

validate_every: 2000
visualize_every: 500
checkpoint_every: 500

#resume_from: "out/kitti_360/kitti_360_backend-None-1_20230824-093207/training_checkpoint_6000.pt"

num_epochs: 25
batch_size: 8 #16

save_best:
    metric: abs_rel # ie_acc # abs_rel
    sign: -1 # 1 # -1

data:
    data_fc: 2
    image_size: [192, 640]
    color_aug: true
    is_preprocessed: true
    fisheye_rotation: [0, -15]
    data_segmentation: true

model_conf:
    arch: "SBTSNet"
    use_code: true
    prediction_mode: default

    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true

    encoder:
        type: "semantic"
        freeze: false
        pretrained: true
        resnet_layers: 50
        num_ch_dec: [32,32,64,128,256]
        d_out: 64

    mlp_coarse:
        type : "resnet"
        n_blocks : 0
        d_hidden : 64

    mlp_fine:
        type : "empty"
        n_blocks : 1
        d_hidden : 128

    mlp_class:
        type : "class_resnet"
        n_blocks : 0
        d_hidden : 64
        n_classes: 10
        class_names: ["unlabeled", "road", "sidewalk", "vegetation", "terrain", "sky", "car", "person", "truck", "wall"]

    z_near: 3
    z_far: 80
    inv_z: true

    n_frames_encoder: 1
    n_frames_render: 2
    frame_sample_mode: kitti360-mono

    sample_mode: patch
    patch_size: 8
    ray_batch_size: 4096

    flip_augmentation: true

    learn_empty: false
    code_mode: z

loss:
    criterion: "l1+ssim"
    invalid_policy: weight_guided
    lambda_edge_aware_smoothness: 0.001
    lambda_sem: 1

scheduler:
    type: step
    step_size: 120000
    gamma: 0.1

renderer:
    n_coarse : 64
    n_fine : 0
    n_fine_depth : 0
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    hard_alpha_cap: true
